// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ai-chat/BestOf.tsx": () => import("../components/mockups/ai-chat/BestOf.tsx"),
  "./components/mockups/ai-chat/ChatInterface.tsx": () => import("../components/mockups/ai-chat/ChatInterface.tsx"),
  "./components/mockups/ai-chat/ChatInterfaceFlyout.tsx": () => import("../components/mockups/ai-chat/ChatInterfaceFlyout.tsx"),
  "./components/mockups/ai-chat/ConversationView.tsx": () => import("../components/mockups/ai-chat/ConversationView.tsx"),
  "./components/mockups/ai-chat/ConversationViewBestOf.tsx": () => import("../components/mockups/ai-chat/ConversationViewBestOf.tsx"),
  "./components/mockups/ai-chat/ConversationViewMarketplace.tsx": () => import("../components/mockups/ai-chat/ConversationViewMarketplace.tsx"),
  "./components/mockups/ai-chat/FinalDesign.tsx": () => import("../components/mockups/ai-chat/FinalDesign.tsx"),
  "./components/mockups/ai-chat/FinalDesignCollapsible.tsx": () => import("../components/mockups/ai-chat/FinalDesignCollapsible.tsx"),
  "./components/mockups/ai-chat/FinalDesignMarket.tsx": () => import("../components/mockups/ai-chat/FinalDesignMarket.tsx"),
  "./components/mockups/ai-chat/FinalDesignSettings.tsx": () => import("../components/mockups/ai-chat/FinalDesignSettings.tsx"),
  "./components/mockups/ai-chat/InstrumentPanel.tsx": () => import("../components/mockups/ai-chat/InstrumentPanel.tsx"),
  "./components/mockups/ai-chat/LandingHero.tsx": () => import("../components/mockups/ai-chat/LandingHero.tsx"),
  "./components/mockups/ai-chat/LightWorkspace.tsx": () => import("../components/mockups/ai-chat/LightWorkspace.tsx"),
  "./components/mockups/ai-chat/MarketplaceHub.tsx": () => import("../components/mockups/ai-chat/MarketplaceHub.tsx")
};
